language: node_js

before_script:
  - npm install -g gatsby-cli
  - cd plugins/gatsby-source-eventbrite-multi-accounts/node_modules
  - npm install && cd .. && cd ..

node_js:
- "13"

cache:
  directories:
  - node_modules
  - plugins/gatsby-source-eventbrite-multi-accounts/node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master

script:
  - "npm run test"
after_success:
  - "npm run deploy"