language: node_js

before_script:
  - npm install -g gatsby-cli
  - cd plugins/gatsby-source-eventbrite-multi-accounts/
  - npm install && cd .. && cd ..

node_js:
- "13"

cache:
  directories:
  - node_modules

deploy:
  fqdn: dataviz.shef.ac.uk
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master

script:
  - "npm run test"
after_success:
  - "npm run deploy"