language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "13"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master

script:
  - "npm run test"
after_success:
  - "npm run deploy"